# Generated by Django 3.1 on 2021-07-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_methond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_methond',
            new_name='login_method',
        ),
    ]
